# Generated by Django 4.2.4 on 2024-18-03 05:49
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_num_of_guests_booking_no_of_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
    ]
